//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int idcompra { get; set; }
        public string NoCompra { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public string Suplidor { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual compras compras1 { get; set; }
        public virtual compras compras2 { get; set; }
    }
}
