//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNcf
    {
        public int idDetalle { get; set; }
        public Nullable<int> idNcf { get; set; }
        public Nullable<int> iddocumento { get; set; }
        public Nullable<int> tipodocumento { get; set; }
        public Nullable<int> secuencia { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> usuarioid { get; set; }

        public DetalleNcf(int? idNcf, int? iddocumento, int? tipodocumento, int? secuencia, int? status, int? empresaid, int? usuarioid, int? idncfsecuencia)
        {
            this.idNcf = idNcf;
            this.iddocumento = iddocumento;
            this.tipodocumento = tipodocumento;
            this.secuencia = secuencia;
            this.status = status;
            this.empresaid = empresaid;
            this.usuarioid = usuarioid;
            this.idncfsecuencia = idncfsecuencia;
        }

        public DetalleNcf()
        {
        }

        public Nullable<int> idncfsecuencia { get; set; }
    }
}
