//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacion
    {
        public int idDetalle { get; set; }
        public Nullable<int> idcotizacion { get; set; }
        public string Ref { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public string itbis { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> totaldescuento { get; set; }

        public DetalleCotizacion(int? idcotizacion, string @ref, string descripcion, int? cantidad, decimal? precio, decimal? descuento, string itbis, decimal? importe, decimal? totaldescuento, cotizacion cotizacion)
        {
            this.idcotizacion = idcotizacion;
            Ref = @ref;
            this.descripcion = descripcion;
            this.cantidad = cantidad;
            this.precio = precio;
            this.descuento = descuento;
            this.itbis = itbis;
            this.importe = importe;
            this.totaldescuento = totaldescuento;
            this.cotizacion = cotizacion;
        }

        public DetalleCotizacion()
        {
        }

        public virtual cotizacion cotizacion { get; set; }
    }
}
