//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int idInventario { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string codigodebarras { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string itbis { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string nota { get; set; }
        public string CodigoProducto { get; set; }
        public string Foto { get; set; }
        public string status { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> usuarioid { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Login Login { get; set; }
    }
}
