//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public int idNCF { get; set; }
        public string Tipo { get; set; }
        public string Estatus { get; set; }
        public string NoNCF { get; set; }
        public string nombreEmpresa { get; set; }
        public string rnc { get; set; }
        public string direccionEmpresa { get; set; }
    }
}
