//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public int idNCF { get; set; }
        public string NombreComp { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> usuarioid { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> tipodocumento { get; set; }
        public string numerodesecuencia { get; set; }

        public virtual Empresa Empresa { get; set; }
        public virtual Login Login { get; set; }
    }
}
