//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NcFsecuencia
    {
        public int idDetalle { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fechavence { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> idncf { get; set; }
        public Nullable<int> desde { get; set; }
        public Nullable<int> hasta { get; set; }
        public Nullable<int> usado { get; set; }
        public Nullable<int> autorizacion { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> usuarioid { get; set; }
    }
}
