//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.Inventario1 = new HashSet<Inventario>();
        }
    
        public int idProducto { get; set; }
        public string codigobarra { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idtipo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string itbis { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string nota { get; set; }
        public string Inventario { get; set; }
        public string CodProducto { get; set; }
        public string Foto { get; set; }
        public string Status { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> usuarioid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario1 { get; set; }
        public virtual tiposproductos tiposproductos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Login Login { get; set; }
    }
}
